### ISSUE TITLE
Username change causes application error

### ISSUE THREAD

**Issue by closetgeekshow** [pdelfan/ouranos#10]
When I changed my username to domain (after having already logged in with my old username), I got an application error. Presumably because your DID number changes or something when you do then. 

I wiped the site data and relogged in, but there should probably be a better error state.

**Comment by closetgeekshow** [comment]
this is my vercel log for the event

```
l [Error]: Profile not found
    at l.call (/var/task/.next/server/chunks/7016.js:1:514304)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async n (/var/task/.next/server/chunks/5399.js:6:19433)
    at async x (/var/task/.next/server/chunks/5399.js:6:18942) {
  error: 'InvalidRequest',
  headers: {
    'access-control-allow-origin': '*',
    'cache-control': 'private',
    'content-length': '56',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 16 Nov 2024 18:50:59 GMT',
    etag: 'W/"38-tAZLZU2ZqXXtTINJ8yohUtX3PCk"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '3000',
    'ratelimit-policy': '3000;w=300',
    'ratelimit-remaining': '2999',
    'ratelimit-reset': '1731783359',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Authorization, Accept-Encoding',
    'x-powered-by': 'Express'
  },
  success: false,
  status: 400,
  digest: '3220882974'
```

**Comment by pdelfan** [comment]
> this is my vercel log for the event
> 
> ```
> l [Error]: Profile not found
>     at l.call (/var/task/.next/server/chunks/7016.js:1:514304)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async n (/var/task/.next/server/chunks/5399.js:6:19433)
>     at async x (/var/task/.next/server/chunks/5399.js:6:18942) {
>   error: 'InvalidRequest',
>   headers: {
>     'access-control-allow-origin': '*',
>     'cache-control': 'private',
>     'content-length': '56',
>     'content-type': 'application/json; charset=utf-8',
>     date: 'Sat, 16 Nov 2024 18:50:59 GMT',
>     etag: 'W/"38-tAZLZU2ZqXXtTINJ8yohUtX3PCk"',
>     'keep-alive': 'timeout=90',
>     'ratelimit-limit': '3000',
>     'ratelimit-policy': '3000;w=300',
>     'ratelimit-remaining': '2999',
>     'ratelimit-reset': '1731783359',
>     'strict-transport-security': 'max-age=63072000',
>     vary: 'Authorization, Accept-Encoding',
>     'x-powered-by': 'Express'
>   },
>   success: false,
>   status: 400,
>   digest: '3220882974'
> ```

Thanks for bringing this up, you're right, this should be gracefully handled.
